const RAISE_TEMP = 'RAISE_TEMP';
const LOWER_TEMP = 'LOWER_TEMP';
const UNDO = 'UNDO';
const REDO = 'REDO';
const UNDO_FURNITURE = 'UNDO_FURNITURE';
const REDO_FURNITURE = 'REDO_FURNITURE';
const ADD_FURNITURE = 'ADD_FURNITURE';

export {RAISE_TEMP, LOWER_TEMP, UNDO, REDO, ADD_FURNITURE, UNDO_FURNITURE, REDO_FURNITURE};
